---
title: "Isotope Sampling Snow"
author: "Natalie Ceperley"
date: "November 25th, 2025"
toc: true
format:
  html:
    html-math-method: katex
    code-tools: true
    self-contained: true
execute:
  warning: false
---


## Goal 

## Equiment

## Preparation

## Field Steps

SNOW SAMPLING => Also chapter for WG3

In general, precipitation varies by elevation, so as a best practice, rain collectors should be placed along an elevation gradient if it exists. 
Travel through the a tree or vegetation canopy can modify the isotopic values of precipitation, thus it is important to ensure an open path to the sky.  
1.2.2.	Collecting ice, snow, snowpack and snow melt
Rain water collectors (e.g. the Palmex RS1 described above) can be used as a simple method to collect snow in some cases.  Although the collector is not optimized for snow, the designers recommend adding an additional 30 cm long tube on top of the funnel. They claim that it will collect snow quantitatively with loss only attributable to wind.  This will only work if the total volume of snow between melting moments does not exceed the storage capacity of the combined funnel and tube.  However, additional errors can be introduced because accumulated snow can sublimate before entering into the collection flask, further distorting the isotope signal, and if temperatures are below freezing, it will be impossible to sample the bottle without thawing it. Thawing water that is not in a hermetically sealed container with minimal head space can introduce additional fractional.  Finally, there is little need to use such a collection device for snow, because snow accumulates naturally and sampling directly in the natural snow-pack will capture the natural accumulation, freezing, and thawing more accurately than in an installed collector.  

Essentially snow sampling is quite simple.  It requires high-quality bags that can be hermetically sealed in field conditions  and won't be easily punctured (commercial grade food bags work well), an insulated container (i.e., a cooler or cooler bag) that can prevent rapid phase change and corresponding evaporation (similar to the best practices recommended for water sample transport and storage), a cool environment where the samples can thaw (i.e., a refrigerator), and then the same vials used for water sampling and storage.   When snow is placed in the sampling bags, attention should be made to reduce air as much as possible. The bags with thawed snow should be well mixed in case of condensation on the wall of the bag and then sub-sampled by pouring in to water sample vials.  If necessary they debris can be filtered at this point.   Attention, old snow pack often contains biota that might fractionate stored water in the right conditions.  In this case, the samples should be filtered. In the field, a snow shovel or trowel might be of interest to facilitate snow collection.  If a fixed volume is required, then a cylinder or fixed volume device will be desired. Finally, for quantitative and accompanying data, it is necessary to have a snow probe (avalanche probe) or tape measure or meter stick to accurately measure snow depth.

When sampling the snow pack directly, one must consider which variables and values are important to the study.  Namely: which snow is of interest, new snow, old snow, the layers of snow snow pack, a composite value for the entire snow pack, and the corresponding amount measurements snow water equivalent, snow pack density, and snow texture.  If the site is regularly sampled and visited immediately following new snowfall events, then only sampling the uppermost layer of the snow may be sufficient.  However, if a complete picture of the isotopic values in the snow pack is desired, then a careful snow profile with accompanying samples must be made.   A composite sample that is representative of the entire snow pack may be a compromise between the two.  In an ideal scenario, snow sampling will occur near a winter adapted meteorological station to have an accurate picture of snow fall and accumulation, but unfortunately these are often few and far between.  

Snow profiles are basic tools used to observe the snow pack, often to gauge snow pack stability.   Several online tutorials are available.  The basic idea is to dig a hole to the ground surface with a smooth "wall", enter into this whole and measure each layers depth, observe each layer's texture, and sample each layer for subsequent isotope analysis.  Layers are usually defined by texture. Additionally a volumetric consistent sample (often with a tube) can be made and weighed, often with a spring scale, to obtain the snow water equivalent.  Finally, snow temperature is often desired, and for this a corresponding thermometer is necessary.  In the case of deep snow packs, attention must be paid to pack stability to prevent local avalanche triggering.  In the case of a composite sample, no effort is made to define layers, rather the whole profile is stuffed evenly into a sampling bag (i.e. a small amount from all the layers).   If just the top layer is sample, then only the fresh snow is put into the bag. If full profiles are made and a hole is dug, then a new exactly location must be chosen on each subsequent visit to capture the undisturbed snow pack. 

%For the majority of observations, snow density was measured in 10 cm increments from the snow surface to the ground using a 1000 cc Snowmetric RIP1 density cutter (Kelly cutter). A combination of depth and density provides point-based SWE estimates at the site. At some sites, collections were conducted with Federal or SnowHydro samplers (coring tubes). In those cases, three to five cores were taken at each site and the average of all collections used as the mean SWE estimate.


For many hydrological applications, the snow pack is not actually of interest.   Instead, the hydrologist may wish to sample the snow melt, or the water that will enter the hydrological system from the snow pack.  Sampling snow melt is not straight forward, but at this point several snow melt lysimeters have been proposed that simultaneously measure and collect snow melt.   Because in many systems snow melt occurs at a very high rate at certain times of year, careful attention must be paid to ensure that these snow melt lysimeters survive a season under the snow and can handle the volume of melt that is expected during the spring melt period.  Additionally, snow melt may be accompanied by significant debris flow, which presents another challenge to field instrumentation.  Lysimeters are essentially rain gauges that are placed before snow accumulation and spend much of the winter months buried.  They are connected to a collector where the snow melt accumulates.  Ideally this is accessible for sampling throughout the snow season.  Other designs have been explored such as a weight lysimeter.  


There is not a clear consensus on isotopic variation in the snow, and clearly snow depth can vary tremendously on a small resolution, so it can be expected that isotopic values can as well.  There fore, attention must be paid to the spatial resolution of sampling given the specific research questions and study site characteristics.  

Sampling ice is perhaps the easiest, if the ice is easily accessible.   A normal ice screw that is used for climbing can be used to "drill" a "carrot" that can either be place directly into a water sampling vial or into a snow sampling bag and transferred when it is thaws.  Debris in ice samples can also be considerable, so filtration might be required. Longer screws are more desirable as they will the provide an average value over a greater depth.   In some cases an ice corer may be necessary, in order to access deeper ice.  In this case, sample storage and transport is more involved, and division of the ice core into layers may be desired to capture the variation by depth.  

The most important thing to remember when sampling snow is to be attentive to the saftey of the field workers.  

1.3 Accompanying measurements

We have discussed the importance of volume when sampling precipitation.  Amount of stream flow, depth of water, etc . should be considered when sampling surface water and depth to ground water when water is sampled below the surface.   Temperature and electrical conductivity are simple measures that are invaluable to isotope interpretation and ideally are simultaneously recorded.  Additional geochemical tracers (or biological) may be of interest depending on the application.   

The two most important pieces of metadata that should always accompany isotope values are the time and date of the sample and the exact location.   In the case of repeat samples, it is helpful to fix locations and name them in a catchment or study area and repeatedly sample in those places.  Relying purely on GPS measurements or cell phone tracking location can be frustrating later on because, in the case of less-expensive devices, the reading will vary according to satellite communication and availability, which can depend on highly variable conditions or direct line of sight with satellites, which is limited in for example, mountain environments.  


%https://snowmetrics.com/
%https://issuu.com/americanavalanche/docs/aaa_swag_sample

## Follow-up 

## Tips 

## References